-- +goose Up

BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TABLE roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE operators (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name jsonb NOT NULL,
  code varchar(50) NOT NULL UNIQUE,
  hotline varchar(30),
  email varchar(320),
  status varchar(30) NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar(255) NOT NULL,
  email varchar(320) UNIQUE,
  phone varchar(30) UNIQUE,
  role_id integer,
  operator_id integer,
  password text NOT NULL,
  language varchar(10) NOT NULL DEFAULT 'vi',
  status varchar(30) NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE INDEX idx_users_role_id ON users USING btree (role_id);
CREATE INDEX idx_users_operator_id ON users USING btree (operator_id);

-- Translation search indexes
CREATE INDEX idx_operators_name_vi_trgm ON operators USING gin ((lower(COALESCE(name ->> 'vi', ''))) gin_trgm_ops);
CREATE INDEX idx_operators_name_en_trgm ON operators USING gin ((lower(COALESCE(name ->> 'en', ''))) gin_trgm_ops);

-- -----------------------------------------------------------------------------
-- ADMINISTRATIVE AREAS & PHYSICAL LOCATIONS
-- -----------------------------------------------------------------------------
CREATE TABLE administrative_areas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer,
  name jsonb NOT NULL,
  code varchar(50),
  level varchar(30) NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE UNIQUE INDEX uq_administrative_areas_level_code ON administrative_areas USING btree (level, code)
  WHERE code IS NOT NULL;
CREATE INDEX idx_administrative_areas_parent_id ON administrative_areas USING btree (parent_id);
CREATE INDEX idx_administrative_areas_name_vi_trgm ON administrative_areas USING gin ((lower(COALESCE(name ->> 'vi', ''))) gin_trgm_ops);
CREATE INDEX idx_administrative_areas_name_en_trgm ON administrative_areas USING gin ((lower(COALESCE(name ->> 'en', ''))) gin_trgm_ops);

CREATE TABLE locations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  administrative_area_id integer,
  operator_id integer,
  name jsonb NOT NULL,
  type varchar(40) NOT NULL,
  address text,
  latitude numeric(9,6),
  longitude numeric(9,6),
  metadata jsonb DEFAULT '{}'::jsonb,
  status varchar(30) NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE INDEX idx_locations_administrative_area_id ON locations USING btree (administrative_area_id);
CREATE INDEX idx_locations_operator_id ON locations USING btree (operator_id);
CREATE INDEX idx_locations_name_vi_trgm ON locations USING gin ((lower(COALESCE(name ->> 'vi', ''))) gin_trgm_ops);
CREATE INDEX idx_locations_name_en_trgm ON locations USING gin ((lower(COALESCE(name ->> 'en', ''))) gin_trgm_ops);

-- -----------------------------------------------------------------------------
-- ROUTES & ROUTE STOPS
-- -----------------------------------------------------------------------------
CREATE TABLE routes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id integer NOT NULL,
  origin_id integer NOT NULL,
  destination_id integer NOT NULL,
  name jsonb NOT NULL,
  distance_km numeric(10,2),
  estimated_duration_minutes integer,
  status varchar(30) NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  route_snapshot jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE INDEX idx_routes_operator_id ON routes USING btree (operator_id);
CREATE INDEX idx_routes_origin_destination ON routes USING btree (origin_id, destination_id);
CREATE INDEX idx_routes_name_vi_trgm ON routes USING gin ((lower(COALESCE(name ->> 'vi', ''))) gin_trgm_ops);
CREATE INDEX idx_routes_name_en_trgm ON routes USING gin ((lower(COALESCE(name ->> 'en', ''))) gin_trgm_ops);

-- route_snapshot is a display/read projection, therefore no GIN index is created.

CREATE TABLE route_stops (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id integer NOT NULL,
  location_id integer NOT NULL,
  stop_order integer NOT NULL,
  stop_type varchar(40) NOT NULL,
  arrival_offset_minutes integer,
  departure_offset_minutes integer,
  public_note jsonb DEFAULT '{}'::jsonb,
  internal_note text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_route_stops_route_order
  ON route_stops USING btree (route_id, stop_order);
CREATE INDEX idx_route_stops_location_id ON route_stops USING btree (location_id);

-- public_note is display content and is not indexed by default.

-- -----------------------------------------------------------------------------
-- VEHICLES
-- -----------------------------------------------------------------------------
CREATE TABLE vehicles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id integer NOT NULL,
  plate_number varchar(30) NOT NULL UNIQUE,
  vehicle_type varchar(40) NOT NULL,
  total_seats integer NOT NULL,
  status varchar(30) NOT NULL,
  seat_layout jsonb DEFAULT '{}'::jsonb,
  amenities jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE INDEX idx_vehicles_operator_id ON vehicles USING btree (operator_id);
CREATE INDEX idx_vehicles_amenities_gin ON vehicles USING gin (amenities jsonb_path_ops);

-- -----------------------------------------------------------------------------
-- TRIPS
-- -----------------------------------------------------------------------------
CREATE TABLE trips (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id integer NOT NULL,
  route_id integer NOT NULL,
  vehicle_id integer NOT NULL,
  origin_id integer NOT NULL,
  destination_id integer NOT NULL,
  departure_time timestamptz NOT NULL,
  arrival_time timestamptz,
  base_price bigint NOT NULL,
  status varchar(30) NOT NULL,
  available_seats_count integer DEFAULT 0,
  booked_seats_count integer DEFAULT 0,
  held_seats_count integer DEFAULT 0,
  searchable_snapshot jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE INDEX idx_trips_origin_destination_departure ON trips USING btree (origin_id, destination_id, departure_time);
CREATE INDEX idx_trips_route_departure ON trips USING btree (route_id, departure_time);
CREATE INDEX idx_trips_operator_departure ON trips USING btree (operator_id, departure_time);
CREATE INDEX idx_trips_vehicle_departure ON trips USING btree (vehicle_id, departure_time);
CREATE INDEX idx_trips_departure_time ON trips USING btree (departure_time);

-- searchable_snapshot is selected for display but primary filtering uses columns,
-- therefore no broad GIN index is created.

-- -----------------------------------------------------------------------------
-- BOOKINGS
-- -----------------------------------------------------------------------------
CREATE TABLE bookings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code varchar(40) NOT NULL UNIQUE,
  user_id integer,
  trip_id integer NOT NULL,
  operator_id integer NOT NULL,
  status varchar(40) NOT NULL,
  payment_status varchar(40) NOT NULL,
  total_amount bigint NOT NULL,
  booked_seats_count integer NOT NULL,
  contact_info jsonb DEFAULT '{}'::jsonb,
  trip_snapshot jsonb DEFAULT '{}'::jsonb,
  seats_snapshot jsonb DEFAULT '{}'::jsonb,
  expired_at timestamptz,
  cancelled_at timestamptz,
  cancel_reason text,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE INDEX idx_bookings_user_created_at ON bookings USING btree (user_id, created_at DESC);
CREATE INDEX idx_bookings_trip_id ON bookings USING btree (trip_id);
CREATE INDEX idx_bookings_operator_created_at ON bookings USING btree (operator_id, created_at DESC);
CREATE INDEX idx_bookings_expired_at ON bookings USING btree (expired_at);

-- Snapshots are transaction history read models; no GIN indexes are created.

-- -----------------------------------------------------------------------------
-- SEAT INVENTORY
-- -----------------------------------------------------------------------------
CREATE TABLE seat_inventories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id integer NOT NULL,
  seat_no varchar(30) NOT NULL,
  floor integer,
  row_no integer,
  column_no integer,
  seat_type varchar(40),
  price bigint NOT NULL,
  status varchar(30) NOT NULL,
  held_until timestamptz,
  held_by_user_id integer,
  booking_id integer,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_seat_inventories_trip_seat
  ON seat_inventories USING btree (trip_id, seat_no);
CREATE INDEX idx_seat_inventories_booking_id ON seat_inventories USING btree (booking_id);
CREATE INDEX idx_seat_inventories_held_by_user_id ON seat_inventories USING btree (held_by_user_id);
CREATE INDEX idx_seat_inventories_held_until ON seat_inventories USING btree (held_until);

-- No standalone status/type index is created. The unique (trip_id, seat_no) index
-- already supports loading a trip's complete seat map efficiently.

-- -----------------------------------------------------------------------------
-- PAYMENTS
-- -----------------------------------------------------------------------------
CREATE TABLE payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id integer NOT NULL,
  provider varchar(40) NOT NULL,
  method varchar(40) NOT NULL,
  amount bigint NOT NULL,
  status varchar(30) NOT NULL,
  merchant_transaction_ref varchar(100) NOT NULL UNIQUE,
  gateway_transaction_id varchar(150),
  provider_payload jsonb DEFAULT '{}'::jsonb,
  paid_at timestamptz,
  failed_at timestamptz,
  refunded_at timestamptz,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_payments_booking_created_at ON payments USING btree (booking_id, created_at DESC);
CREATE UNIQUE INDEX uq_payments_provider_gateway_transaction ON payments USING btree (provider, gateway_transaction_id)
WHERE gateway_transaction_id IS NOT NULL;

-- provider_payload is retained for gateway audit/debug and is not indexed.

-- -----------------------------------------------------------------------------
-- CHECK-IN / BOARDING
-- -----------------------------------------------------------------------------
CREATE TABLE passenger_checkins (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seat_inventory_id integer NOT NULL UNIQUE,
  checked_in_by_user_id integer,
  checked_in_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  note text,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_passenger_checkins_checked_in_by_user_id ON passenger_checkins USING btree (checked_in_by_user_id);
CREATE INDEX idx_passenger_checkins_checked_in_at ON passenger_checkins USING btree (checked_in_at);

-- -----------------------------------------------------------------------------
-- PROMOTIONS
-- -----------------------------------------------------------------------------
CREATE TABLE promotions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id integer,
  code varchar(50) NOT NULL UNIQUE,
  name jsonb NOT NULL,
  description jsonb DEFAULT '{}'::jsonb,
  terms_and_conditions jsonb DEFAULT '{}'::jsonb,
  discount_type varchar(30) NOT NULL,
  discount_value bigint NOT NULL,
  max_discount_amount bigint,
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  status varchar(30) NOT NULL,
  conditions jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,

  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE INDEX idx_promotions_operator_id ON promotions USING btree (operator_id);
CREATE INDEX idx_promotions_start_at ON promotions USING btree (start_at);
CREATE INDEX idx_promotions_end_at ON promotions USING btree (end_at);
CREATE INDEX idx_promotions_name_vi_trgm ON promotions USING gin ((lower(COALESCE(name ->> 'vi', ''))) gin_trgm_ops);
CREATE INDEX idx_promotions_name_en_trgm ON promotions USING gin ((lower(COALESCE(name ->> 'en', ''))) gin_trgm_ops);

-- Supports containment queries such as conditions @> '{"minimum_amount": 500000}'.
CREATE INDEX idx_promotions_conditions_gin ON promotions USING gin (conditions jsonb_path_ops);

CREATE TABLE booking_promotions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id integer NOT NULL,
  promotion_id integer NOT NULL,
  discount_amount bigint NOT NULL,
  booking_promotion_snapshot jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_booking_promotions_promotion_id ON booking_promotions USING btree (promotion_id);

-- -----------------------------------------------------------------------------
-- NOTIFICATIONS
-- -----------------------------------------------------------------------------
CREATE TABLE notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  booking_id integer,
  locale varchar(10) NOT NULL DEFAULT 'vi',
  type varchar(50) NOT NULL,
  channel varchar(30) NOT NULL,
  title varchar(500) NOT NULL,
  content text NOT NULL,
  status varchar(30) NOT NULL,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notifications_user_created_at ON notifications USING btree (user_id, created_at DESC);
CREATE INDEX idx_notifications_booking_id ON notifications USING btree (booking_id);
CREATE INDEX idx_notifications_sent_at ON notifications USING btree (sent_at);

-- -----------------------------------------------------------------------------
-- REVIEWS
-- -----------------------------------------------------------------------------
CREATE TABLE reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id integer NOT NULL UNIQUE,
  user_id integer NOT NULL,
  operator_id integer NOT NULL,
  rating smallint NOT NULL,
  comment text,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,

  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz
);

CREATE INDEX idx_reviews_operator_created_at ON reviews USING btree (operator_id, created_at DESC);
CREATE INDEX idx_reviews_user_created_at ON reviews USING btree (user_id, created_at DESC);

-- -----------------------------------------------------------------------------
-- AUDIT LOGS
-- -----------------------------------------------------------------------------
CREATE TABLE audit_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id integer,
  operator_id integer,
  action varchar(100) NOT NULL,
  entity_type varchar(100) NOT NULL,
  entity_id integer,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_actor_created_at ON audit_logs USING btree (actor_user_id, created_at DESC);
CREATE INDEX idx_audit_logs_operator_created_at ON audit_logs USING btree (operator_id, created_at DESC);
CREATE INDEX idx_audit_logs_entity_created_at ON audit_logs USING btree (entity_type, entity_id, created_at DESC);

-- audit metadata is not globally indexed because its shape is intentionally flexible.

-- -----------------------------------------------------------------------------
-- Soft-delete notes
-- -----------------------------------------------------------------------------
-- Soft delete is used only for mutable/master or user-visible business entities:
-- operators, users, administrative_areas, locations, routes, vehicles, trips,
-- bookings, promotions and reviews. Append-only/history/detail tables are retained
-- without soft-delete columns and are handled by status or retention jobs.
--
-- No standalone B-tree index is created on `deleted` because it has very low
-- cardinality. Add workload-specific partial indexes such as
--   CREATE INDEX ... ON trips (...) WHERE deleted = false;
-- after observing real query patterns. Application queries must explicitly use
-- `deleted = false` for active records and deletion jobs should set both fields.

-- -----------------------------------------------------------------------------
-- updated_at triggers
-- -----------------------------------------------------------------------------
CREATE TRIGGER trg_operators_set_updated_at
BEFORE UPDATE ON operators
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_administrative_areas_set_updated_at
BEFORE UPDATE ON administrative_areas
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_locations_set_updated_at
BEFORE UPDATE ON locations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_routes_set_updated_at
BEFORE UPDATE ON routes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_route_stops_set_updated_at
BEFORE UPDATE ON route_stops
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_vehicles_set_updated_at
BEFORE UPDATE ON vehicles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_trips_set_updated_at
BEFORE UPDATE ON trips
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_bookings_set_updated_at
BEFORE UPDATE ON bookings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_seat_inventories_set_updated_at
BEFORE UPDATE ON seat_inventories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_payments_set_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_promotions_set_updated_at
BEFORE UPDATE ON promotions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_reviews_set_updated_at
BEFORE UPDATE ON reviews
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;

-- +goose Down

BEGIN;

DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS booking_promotions;
DROP TABLE IF EXISTS promotions;
DROP TABLE IF EXISTS passenger_checkins;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS seat_inventories;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS route_stops;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS administrative_areas;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS operators;
DROP TABLE IF EXISTS roles;

DROP FUNCTION IF EXISTS set_updated_at();

COMMIT;